JambulaTV: Fix issue where jambulatv-mifi-query writes 'MIFI_COOKIE_JAR'            file to current working directory
* Save cookie jar file to temporary and not the current working directory

* Remove cookie jar file after login process and at completion of script
  execution i.e. clean_up functions

* Add, export TERM variable and change exit code to 254 when login fails

diff --git a/bin/jambulatv-mifi-query b/bin/jambulatv-mifi-query
--- a/bin/jambulatv-mifi-query
+++ b/bin/jambulatv-mifi-query
@@ -22,17 +22,20 @@
 
 # Variables
 CURL_CMD="/usr/bin/curl"
-CURL_OPTS="-L -s -S -m 60 -A 'Mozilla/5.0' -k -b MIFI_COOKIE_JAR -c MIFI_COOKIE_JAR"
+COOKIE_JAR_FILE=/tmp/mifi_cookie_jar.$$
+CURL_OPTS="-L -s -S -m 60 -A 'Mozilla/5.0' -k -b $COOKIE_JAR_FILE -c $COOKIE_JAR_FILE"
 MIFI_IP_ADDRESS=$1
 MIFI_LOGIN_ADMIN_USER="$2"
 MIFI_LOGIN_ADMIN_PASSWORD="$3"
 MIFI_LOGIN_ADMIN_PASSWORD_BASE64=$(printf "$(printf "$MIFI_LOGIN_ADMIN_PASSWORD" | sha256sum |  cut -d ' ' -f 1)" | base64 -w 0)
 MIFI_ACTION=$4
-MIFI_LOGIN_OUTPUT_FILE=/tmp/router_login
+MIFI_LOGIN_OUTPUT_FILE=/tmp/mifi_login_output.$$
 HTTP_BROWSER_USERAGENT="Mozilla/5.0"
 HTTP_BROWSER_COMMAND="$CURL_CMD $CURL_OPTS"
 SMS_MESSAGE_RAW_OUTPUT_FILE=/tmp/router_sms_message
 HOSTS_CONNECTED_OUTPUT_FILE=/tmp/router_wifi_connected_hosts
+TERM=linux
+export TERM
 
 
 
@@ -96,9 +99,6 @@ MIFI_LOGIN_SERVER_PASSWORD_BASE64="$(printf "$(printf "${MIFI_ADMIN_USER_PASSWOR
 # Login
 login () {
 server_session_token_info
-#
-# Remove any existing login output file
-[[ -e $MIFI_LOGIN_OUTPUT_FILE ]] && rm -f $MIFI_LOGIN_OUTPUT_FILE
 # Connect and Login
 $HTTP_BROWSER_COMMAND -o $MIFI_LOGIN_OUTPUT_FILE $HTTP_BROWSER_URL/api/user/login \
 	-H "__RequestVerificationToken: $MIFI_LOGIN_SERVER_TOKEN" \
@@ -108,6 +108,8 @@ $HTTP_BROWSER_COMMAND -o $MIFI_LOGIN_OUTPUT_FILE $HTTP_BROWSER_URL/api/user/logi
 	-d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Username>$MIFI_LOGIN_ADMIN_USER</Username><Password>$(printf "$(printf "$MIFI_LOGIN_ADMIN_USER$MIFI_LOGIN_ADMIN_PASSWORD_BASE64$MIFI_LOGIN_SERVER_TOKEN" | sha256sum | cut -d ' ' -f 1)" | base64 -w 0)</Password><password_type>4</password_type></request>"
 # Get login response
 LOGIN_RESPONSE=$(grep -oP "(?<=<response>).+?(?=</response>)" $MIFI_LOGIN_OUTPUT_FILE)
+# Remove temp mifi login output file
+[[ -e $MIFI_LOGIN_OUTPUT_FILE ]] && rm -f $MIFI_LOGIN_OUTPUT_FILE
 if [ "$LOGIN_RESPONSE" = "OK" ];
 then
 echo "Logged in to your WiFi router"
@@ -125,7 +127,7 @@ Login response: <$LOGIN_RESPONSE>
 $MIFI_LOGIN_ADMIN_PASSWORD_BASE64
 
 EOT
-exit 255
+exit 254
 fi
 }
 
@@ -537,6 +539,11 @@ sms_unread_count
 sms_count_local_inbox
 }
 
+clean_up () {
+# Remove temp cookie jar file
+[[ -e $COOKIE_JAR_FILE ]] && rm -f $COOKIE_JAR_FILE
+}
+
 
 
 #################
@@ -636,3 +643,6 @@ $0 $MIFI_IP_ADDRESS $MIFI_LOGIN_ADMIN_USER $MIFI_LOGIN_ADMIN_PASSWORD info_all
 ;;
 
 esac
+
+# Clean up 
+clean_up
