JambulaTV: Update and improve the tool responsible for system updates            i.e. jambulatv-updater
* Remove FTP related variables as they are now sourced from main
  functions. Also group code responsible for actual update into
  one function i.e. 'run_update'

* Use improved OSD and text notification functions for alerting
  when update is starts/in-progress, completes, or fails

* Use recently added 'wget_download_file' functions to fetch system
  update files from the remote FTP server

* Add the following variable(s) to main functions file:

	- 'JAMBULATV_UPDATES_DOWNLOAD_DIR'
	- 'JAMBULATV_UPDATES_TEMP_DIR'
	- 'JAMBULATV_UPDATES_LOG_DIR'
	- 'JAMBULATV_UPDATES_IN_PROGRESS_NOTIFICATION_MESSAGE'
	- 'JAMBULATV_UPDATES_FAILED_NOTIFICATION_MESSAGE'
	- 'JAMBULATV_UPDATES_COMPLETED_NOTIFICATION_MESSAGE'

* Rename the following variables(s) main functions file:

	- 'WGET_OPTIONS' to 'WGET_OPTS'

* Update copyright notice

* Update FTP server hostname in jambulatv-auto-updates-creator.sh
  utility

diff --git a/bin/jambulatv-updater b/bin/jambulatv-updater
--- a/bin/jambulatv-updater
+++ b/bin/jambulatv-updater
@@ -1,27 +1,19 @@
 #!/bin/sh
-# This script will check for new updates on line; download and install them
-# Jambula Labs @copyright 2016-2017 All rights reserved'
+# This script will check for new updates on line. If updates exist,
+# download and install them
+#
+# Jambula Labs @copyright 2018-2019 All rights reserved
 
-PROJECT_SYSTEM_CONF_DIR=/etc/JambulaTV
-JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE=$PROJECT_SYSTEM_CONF_DIR/updates-ftp-server-cfg
+# Variables
+PROJECT_NAME=JambulaTV
+PROJECT_SYSTEM_CONF_DIR=/etc/$PROJECT_NAME
+PROJECT_FUNCTIONS_FILE=$PROJECT_SYSTEM_CONF_DIR/functions
 
-JAMBULATV_UPDATES_DOWNLOAD_DIR=/var/updates/JambulaTV
-JAMBULATV_UPDATES_TEMP_DIR=/tmp/JambulaTV-updates
-JAMBULATV_UPDATES_LOG_DIR=/var/log/JambulaTV/updates
-JAMBULATV_RELEASE_FILE=/etc/JambulaTV/release
+# Source install functions
+. $PROJECT_FUNCTIONS_FILE
 
 # Source Updates FTP server information i.e. variables
 . $JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE
-
-JAMBULATV_UPDATE_CURRENT_VERSION_FILE=$(basename $JAMBULATV_FTP_SERVER_VERSION_FILE)
-
-WGET_CMD=wget
-WGET_TIMEOUT=20
-WGET_OPTIONS="-q --no-check-certificate --retr-symlinks -T $WGET_TIMEOUT --ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS"
-PING_COUNT=1 #9
-PING_IP_ADDRESS=8.8.8.8
-
-OSD_TOOL_CMD="sudo /usr/bin/jambulatv-osd"
 
 
 
@@ -33,52 +25,101 @@ calc(){
 awk "BEGIN{ print $* }" ;
 }
 
-check_ftp_server_access () {
-# Check for internet connectivity - IMPORTANT: Don't use DNS to ping use actual IP address
-ping -c $PING_COUNT $PING_IP_ADDRESS > /dev/null 2>&1
-EXITVAL=$?
-if [ "$EXITVAL" != "0" ];
-then
-# Quit script, since there's no internet.  Leave exit status at 0 so systemd service works
-exit 0
-fi
+logging_osd_notice_started () {
+# Source notification strings
+set_notifications
+# Print notifciation to stdout and systemd journal 
+print_notification "$JAMBULATV_UPDATES_IN_PROGRESS_NOTIFICATION_MESSAGE" text
+# Print notification using OSD tool
+print_notification "$JAMBULATV_UPDATES_IN_PROGRESS_NOTIFICATION_MESSAGE" osd
+}
+
+logging_osd_notice_failed () {
+# Source notification strings
+set_notifications
+# Print notifciation to stdout and systemd journal 
+print_notification "$JAMBULATV_UPDATES_FAILED_NOTIFICATION_MESSAGE" text
+# Print notification using OSD tool
+print_notification "$JAMBULATV_UPDATES_FAILED_NOTIFICATION_MESSAGE" osd
+}
+
+logging_osd_notice_completed () {
+# Source notification strings
+set_notifications
+# Print notifciation to stdout and systemd journal 
+print_notification "$JAMBULATV_UPDATES_COMPLETED_NOTIFICATION_MESSAGE" text
+# Print notification using OSD tool
+print_notification "$JAMBULATV_UPDATES_COMPLETED_NOTIFICATION_MESSAGE" osd
 }
 
 create_updates_directories () {
-# Create JambulaTV updates directory if it does not exist
+# Create updates directory if it does not exist
 for DIRECTORY in $JAMBULATV_UPDATES_DOWNLOAD_DIR $JAMBULATV_UPDATES_TEMP_DIR $JAMBULATV_UPDATES_LOG_DIR
 do
-[ -d $DIRECTORY ] || mkdir -p $DIRECTORY
+[[ -d $DIRECTORY ]] || sudo mkdir -p $DIRECTORY
+# Give running user the access to updates directories
+RUNNING_USER=$(whoami)
+sudo chown -R $RUNNING_USER $DIRECTORY
 done
 }
 
 query_and_set_versions () {
+# Set current version file
+JAMBULATV_UPDATE_CURRENT_VERSION_FILE=$(basename $JAMBULATV_FTP_SERVER_VERSION_FILE)
 # Download latest update version info file
-$WGET_CMD $WGET_OPTIONS -O $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_VERSION_FILE
+$WGET_CMD $WGET_OPTS --ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS -O \
+	$JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE \
+	ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_VERSION_FILE > /dev/null 2>&1
 #
-# Exit updater if ftp login fails; and log error
-if [ "$?" = "0" ];
+# Log and exit updater if FTP login fails
+if [[ "$?" = "0" ]];
 then
 # Set latest update revision
 JAMBULATV_LATEST_UPDATE_VERSION=$(cat $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE)
 # Lookup current version
-JAMBULATV_INSTALLED_VERSION=$(grep -i Version $JAMBULATV_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
+JAMBULATV_INSTALLED_VERSION=$(grep -i Version $PROJECT_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
 # See if some update versions were skipped
 VERSION_DIFF=$(calc $JAMBULATV_LATEST_UPDATE_VERSION-$JAMBULATV_INSTALLED_VERSION)
 
 else
 
-echo "`date +%Y-%m-%d`: Failed to update JambulaTV because connection to FTP server failed" >> $JAMBULATV_UPDATES_LOG_DIR/errors 2>&1
+# Log failure
+echo "$(date +%Y-%m-%d) $(date +%T) > Failed to update $PROJECT_NAME because connection to FTP server failed" >> $JAMBULATV_UPDATES_LOG_DIR/errors 2>&1
+
+# Alert
+logging_osd_notice_failed
+
+# Quit
 exit 0
 fi
 }
 
 download_updates () {
 # Download tar.gz package
-$WGET_CMD $WGET_OPTIONS -O $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_UPDATES_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz  
+wget_download_file \
+	$JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz \
+	ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_UPDATES_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz \
+	--ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS
 
 # Download Checksum file 
-$WGET_CMD $WGET_OPTIONS -O $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_UPDATES_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt
+wget_download_file \
+	$JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt \
+	ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_UPDATES_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt \
+	--ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS
+
+# Ensure files were downloaded 
+if [[ ! -e $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz ]] || [[ ! -e $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt ]];
+then
+
+# Log and quit if any of the above files is missing
+echo "$(date +%Y-%m-%d) $(date +%T) > Failed to update $PROJECT_NAME because a required file was not downloaded from the FTP server" >> $JAMBULATV_UPDATES_LOG_DIR/errors 2>&1
+
+# Alert
+logging_osd_notice_failed
+
+# Quit
+exit 0
+fi
 }
 
 checksum_compare () {
@@ -86,9 +127,16 @@ checksum_compare () {
 UPDATE_PACKAGE_CHECKSUM_NOW=`openssl dgst -md5 $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz | cut -d "=" -f2 | sed -e 's/ //'`
 UPDATE_PACKAGE_CHECKSUM_ORIG=$(cat $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.checksum.txt)
 # Check checksums
-if [ "$UPDATE_PACKAGE_CHECKSUM_NOW" != "$UPDATE_PACKAGE_CHECKSUM_ORIG" ];
+if [[ "$UPDATE_PACKAGE_CHECKSUM_NOW" != "$UPDATE_PACKAGE_CHECKSUM_ORIG" ]];
 then
-echo "`date +%Y-%m-%d`: Failed to update JambulaTV because the package 'update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz' was tampared with" >> $JAMBULATV_UPDATES_LOG_DIR/errors
+
+# Log tampered with message
+echo "$(date +%Y-%m-%d) $(date +%T) > Failed to update $PROJECT_NAME because the package 'update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz' was tampared with" >> $JAMBULATV_UPDATES_LOG_DIR/errors
+
+# Alert
+logging_osd_notice_failed
+
+# Quit
 exit 0
 fi
 }
@@ -96,51 +144,29 @@ fi
 update_install () {
 # untar package
 tar zxvf $JAMBULATV_UPDATES_TEMP_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz -C $JAMBULATV_UPDATES_DOWNLOAD_DIR
+
 # Run update install file
 . $JAMBULATV_UPDATES_DOWNLOAD_DIR/update-$JAMBULATV_LATEST_UPDATE_VERSION/install.sh
 
 # Update version based after last install
-sed -i "s/Version:v${JAMBULATV_INSTALLED_VERSION}/Version:v${JAMBULATV_LATEST_UPDATE_VERSION}/" $JAMBULATV_RELEASE_FILE
+sudo sed -i "s/Version:v${JAMBULATV_INSTALLED_VERSION}/Version:v${JAMBULATV_LATEST_UPDATE_VERSION}/" $PROJECT_RELEASE_FILE
 }
 
-logging_osd_notice_started () {
-$OSD_TOOL_CMD -m "IMPORTANT: System update in progress.  Please do not power off.  You will be notified when all updates have been completed"
-}
-
-logging_osd_notice_completed () {
-$OSD_TOOL_CMD -m "System updates have completed.  You may now power off if desired"
-}
-
-logging_success  () {
-# Add success info to log file
-echo "$(date +%Y-%m-%d) $(date +%T) > JambulaTV update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz was successfully installed" >> $JAMBULATV_UPDATES_LOG_DIR/messages
-}
-
-
-
-#################
-#  MAIN SCRIPT  #
-#################
-check_ftp_server_access
-create_updates_directories
-query_and_set_versions
-
-# UPDATE
-# ------
-# Quit if JambulaTV is upto update. Leave exit status at 0 so systemd service works
-if [ $(echo "$JAMBULATV_LATEST_UPDATE_VERSION <= $JAMBULATV_INSTALLED_VERSION" | bc -l) = 1 ] || [ "x$JAMBULATV_LATEST_UPDATE_VERSION" = "x" ];
+run_update () {
+# Quit if product is upto update. Leave exit status at 0 so systemd service works
+if [[ $(echo "$JAMBULATV_LATEST_UPDATE_VERSION <= $JAMBULATV_INSTALLED_VERSION" | bc -l) = 1 || "x$JAMBULATV_LATEST_UPDATE_VERSION" = "x" ]];
 then
 exit 0
 
 # Continue, check difference in versions
-elif [ $(echo "$VERSION_DIFF > 0" | bc -l) = 1 ];
+elif [[ $(echo "$VERSION_DIFF > 0" | bc -l) = 1 ]];
 then
 
 # Log on OSD
 logging_osd_notice_started
 
 # Cycle through all available updates
-while [ $(echo "$JAMBULATV_INSTALLED_VERSION < $JAMBULATV_LATEST_UPDATE_VERSION" | bc -l) = 1 ];
+while [[ $(echo "$JAMBULATV_INSTALLED_VERSION < $JAMBULATV_LATEST_UPDATE_VERSION" | bc -l) = 1 ]];
 do
 
 download_updates
@@ -148,11 +174,27 @@ checksum_compare
 update_install
 
 # Query current version
-JAMBULATV_INSTALLED_VERSION=$(grep -i Version $JAMBULATV_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
-
+JAMBULATV_INSTALLED_VERSION=$(grep -i Version $PROJECT_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
 done
 fi
 
-# Log completion
-logging_success 
+# Add completion message to log file
+echo "$(date +%Y-%m-%d) $(date +%T) > $PROJECT_NAME update-$JAMBULATV_LATEST_UPDATE_VERSION.tar.gz was successfully installed" >> $JAMBULATV_UPDATES_LOG_DIR/messages
+
+# Alert
 logging_osd_notice_completed
+}
+
+
+
+#################
+#  MAIN SCRIPT  #
+#################
+
+# Check Internet connectivity
+check_internet_connectivity_ping 0
+create_updates_directories
+query_and_set_versions
+
+# Run update
+run_update
