JambulaTV: Update the Text-2-speech tool 'jambulatv-text2speech' as            follows:
* Add support for merging the TTS generated file with other sound
  clips i.e. Add the option 'concatenate=yes' to list of possible
  CLI arguments that can be called with 'jambulatv-text2speech'

* Also, when merging is requested, do not play the saved TTS file

* Alert using the house speakers if connection to the Text-2-Speech
  API endpoint fails for what ever reason.  Typically, failure will
  happen if you have run out of credits with the TTS API service
  provider. A specific error message showing reason of failure is
  also logged

* Do not proceed with execution if TTS generated file is not in an
  audio format

* Add support for specifying latitude and longitude when querying
  for Weather report

* Update the API key and Instance URL for IBM watson Text-2-Speech
  API service provider

* Use sounds tool to make speaker announcements for static texts
  that don't change e.g. To alert when a command is not recognized

* Update copyright notice

diff --git a/bin/jambulatv-text2speech b/bin/jambulatv-text2speech
--- a/bin/jambulatv-text2speech
+++ b/bin/jambulatv-text2speech
@@ -2,30 +2,29 @@
 # This is the text-to-speech tool used for JambulaTV services.
 # Use it to read time, weather, etc
 #
-# Jambula Labs @copyright 2020-2021 All rights reserved
+# Jambula Labs @copyright 2022-2023 All rights reserved
 
 # Variables
-PROJECT_NAME=JambulaTV
+PROJECT_NAME=MY_PROJECT_NAME
 PROJECT_SYSTEM_CONF_DIR=/etc/$PROJECT_NAME
 PROJECT_GLOBAL_SETTINGS_FILE=$PROJECT_SYSTEM_CONF_DIR/global-settings.cfg
 
 # Source global settings
 . $PROJECT_GLOBAL_SETTINGS_FILE
 
-# Play TTS audio using MPlayer
-TTS_PLAY_CMD="/usr/bin/mpv"
-TTS_AUDIO_DRIVER="$AUDIO_OUTPUT_DRIVER"
-TTS_PLAY_CMD_AUDIO_GAIN=$(echo $@ | awk -F'=' '/gain/ {print $2}')
-#
-if [[ "x$TTS_PLAY_CMD_AUDIO_GAIN" = "x" ]];
-then
-# No audio gain
-TTS_PLAY_CMD_OPTS="--really-quiet -ao $TTS_AUDIO_DRIVER --no-video --pulse-allow-suspended=yes"
+TMPDIR=MY_TMPDIR
 
-else
-# With audio gain
-TTS_PLAY_CMD_OPTS="--really-quiet -ao $TTS_AUDIO_DRIVER --no-video --volume=$TTS_PLAY_CMD_AUDIO_GAIN --pulse-allow-suspended=yes"
-fi
+SOUNDS_TOOL=MY_SOUNDS_TOOL
+SOUNDS_VOLUME_LEVEL=$(echo $@ | awk -F'gain=' '{print $2}' | awk '{print $1}')
+
+TIMEOUT_PROBE="60s"
+TIMEOUT_CMD="/usr/bin/timeout --preserve-status $TIMEOUT_PROBE"
+FFPROBE_CMD="$TIMEOUT_CMD /usr/bin/ffprobe"
+FFPROBE_OPTS_GLOBAL="-hide_banner -loglevel error"
+FFPROBE_OPTS_STREAMS="-show_streams"
+
+TTS_LOG_FILE=$TMPDIR/text2speech.log
+TTS_CONCATENATE_AUDIO=$(echo $@ | awk -F'concatenate=' '{print $2}' | awk '{print $1}')
 
 TTS_OUTPUT_FILE=/var/tmp/tts_output.wav # IMPORTANT: Must be on 'ext4' partition i.e. /var
 #
@@ -79,11 +78,15 @@ Usage:
 	2 - Google
 	3 - IBM Watson (API key required)
 
-For increase in audio volume, add 'gain=level' to the CLI arguments: 
-e.g. gain=0.2
+For adjustment in audio volume, add 'gain=[LEVEL]' to the CLI arguments: 
+e.g. gain=160
+
+Also, if you do not want to play the audio file generated by this tool
+but instead wish to use it for merging purposes, then add 'concatenate=yes 
+to the CLI arguments
 
 EOT
-exit 1
+exit 0
 
 elif [[ "$TTS_ACTION" = "custom" && "x$TTS_CUSTOM_MESSAGE" = "x" ]];
 then
@@ -93,7 +96,7 @@ Usage:
 ./`basename $0` [Speech API] custom [Message]
 
 EOT
-exit 1
+exit 0
 
 fi
 }
@@ -120,7 +123,32 @@ tts_waiting_sound_effects () {
 [ "x$TTS_ACTION" = "x" ] && touch $TTS_OUTPUT_FILE
 #
 # Play waiting for api sound effects
-jambulatv-sounds api $TTS_OUTPUT_FILE
+$SOUNDS_TOOL api $TTS_OUTPUT_FILE
+}
+
+api_test_endpoint_output () {
+# Test to see if file generated is audio
+[[ -s "$TTS_OUTPUT_FILE" ]] && $FFPROBE_CMD $FFPROBE_OPTS_GLOBAL $FFPROBE_OPTS_STREAMS $TTS_OUTPUT_FILE | grep -i audio > /dev/null 2>&1
+IS_AUDIO=$?
+
+# Quit if file was not generated or is not an audio file
+if [[ -s "$TTS_OUTPUT_FILE" ]] && [[ "$IS_AUDIO" = "0" ]];
+then
+break
+
+elif [[ -s "$TTS_OUTPUT_FILE" ]];
+then
+logger -s -t $(basename $0) "Error: API Endpoint: $(cat $TTS_OUTPUT_FILE)"
+$SOUNDS_TOOL alert on_life_support
+$SOUNDS_TOOL alert api_service_error_encountered_try_later
+exit 0
+
+else
+logger -s -t $(basename $0) "Error: API Endpoint: $(cat $TTS_LOG_FILE)"
+$SOUNDS_TOOL alert on_life_support
+$SOUNDS_TOOL alert api_service_error_encountered_try_later
+exit 0
+fi
 }
 
 text2speech_pico () {
@@ -131,23 +159,46 @@ text2speech_pico () {
 text2speech_ispeech () {
 # API Key
 ISPEECH_API_KEY=$(query_mysql_db ispeech_tts_api_key)
+
+# Remove previous TTS log file
+[[ -e $TTS_LOG_FILE ]] && sudo rm -f $TTS_LOG_FILE
+
 # Connect to API Endpoint
-$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -d apikey=$ISPEECH_API_KEY -d text="$1" -d voice=usenglishfemale -d format=mp3 -d frequency=44100 -d bitrate=128 -d speed=1 -d startpadding=1 -d endpadding=1 -d pitch=110 -d filename=$TTS_OUTPUT_FILE "http://api.ispeech.org/api/rest?action=convert"
+$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -d apikey=$ISPEECH_API_KEY -d text="$1" -d voice=usenglishfemale -d format=mp3 -d frequency=44100 -d bitrate=128 -d speed=1 -d startpadding=1 -d endpadding=1 -d pitch=110 -d filename=$TTS_OUTPUT_FILE "http://api.ispeech.org/api/rest?action=convert" > $TTS_LOG_FILE 2>&1
+
+# Test output file
+api_test_endpoint_output
 }
 
 text2speech_google () {
 # API Key
 GOOGLE_API_KEY=$(query_mysql_db google_tts_api_key)
+
+# Remove previous TTS log file
+[[ -e $TTS_LOG_FILE ]] && sudo rm -f $TTS_LOG_FILE
+
 # Connect to API Endpoint
-$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -o $TTS_OUTPUT_FILE "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q="$(echo "$1" | sed -e "s: :%20:g" | sed -e "s:'::g")"&tl=En-us"
+$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -o $TTS_OUTPUT_FILE "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q="$(echo "$1" | sed -e "s: :%20:g" | sed -e "s:'::g")"&tl=En-us" > $TTS_LOG_FILE 2>&1
+
+# Test output file
+api_test_endpoint_output
 }
 
 text2speech_ibm () {
 # API Key
-IBM_API_KEY=$(query_mysql_db watson_tts_api_key)
-IBM_API_ENDPOINT="https://api.eu-gb.text-to-speech.watson.cloud.ibm.com/instances/0d2c8590-15ed-4065-9774-3d681d9a47ee"
+IBM_API_KEY="kO9JEzelVfQjyWt9BIRsuiSjzEZX-a5aXhFiiU-GDMf9"
+IBM_API_INSTANCE="f58b0647-5cf0-4229-9295-90ae8cff2a1d"
+IBM_API_URL="https://api.eu-gb.text-to-speech.watson.cloud.ibm.com"
+IBM_API_ENDPOINT="$IBM_API_URL/instances/$IBM_API_INSTANCE"
+
+# Remove previous TTS log file
+[[ -e $TTS_LOG_FILE ]] && sudo rm -f $TTS_LOG_FILE
+
 # Connect to API Endpoint
-$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -u "apikey:$IBM_API_KEY" -H "Content-Type: application/json" -H "Accept: audio/wav" -d "{\"text\":\"$1\"}" -o $TTS_OUTPUT_FILE "$IBM_API_ENDPOINT/v1/synthesize?voice=en-US_AllisonVoice"
+$CURL_CMD $CURL_OPTS -A "$USER_AGENT" -u "apikey:$IBM_API_KEY" -H "Content-Type: application/json" -H "Accept: audio/wav" -d "{\"text\":\"$1\"}" -o $TTS_OUTPUT_FILE "$IBM_API_ENDPOINT/v1/synthesize?voice=en-US_AllisonVoice" > $TTS_LOG_FILE 2>&1
+
+# Test output file
+api_test_endpoint_output
 }
 
 query_text2speech_engine () {
@@ -244,19 +295,22 @@ say_weather() {
 WEATHER_PERIOD=$3
 WEATHER_API=$4
 WEATHER_DEBUG=$5
-#
+WEATHER_LATITUDE=$6
+WEATHER_LONGITUDE=$7
+
 # Source weather functions
 if [[ "$WEATHER_DEBUG" = "debug" ]];
 then
 # Debugging enabled
-. /usr/bin/jambulatv-weather-api "" "" $WEATHER_PERIOD $WEATHER_API debug
+. /usr/bin/jambulatv-weather-api "$WEATHER_LATITUDE" "$WEATHER_LONGITUDE" $WEATHER_PERIOD $WEATHER_API debug
 else
 # Debugging disabled
-. /usr/bin/jambulatv-weather-api "" "" $WEATHER_PERIOD $WEATHER_API
+. /usr/bin/jambulatv-weather-api "$WEATHER_LATITUDE" "$WEATHER_LONGITUDE" $WEATHER_PERIOD $WEATHER_API
 fi
-# 
+
 # TTS text message
 TTS_TEXT_MESSAGE=$WEATHER_FORECAST_DESCRIPTION
+
 # convert text to audio speech
 query_text2speech_engine
 }
@@ -278,7 +332,10 @@ query_text2speech_engine
 usage
 
 # Remove previously saved TTS audio
-sudo rm -f $TTS_OUTPUT_FILE
+for OUTFILE in $TTS_OUTPUT_FILE $TMPDIR/${TTS_OUTPUT_FILE##*/}
+do
+sudo rm -f $OUTFILE
+done
 
 # Add sound effects while waiting script
 tts_waiting_sound_effects
@@ -294,7 +351,7 @@ say_time
 ;;
 
 weather)
-say_weather "$API" "$TTS_ACTION" "$3" "$4" "$5"
+say_weather "$API" "$TTS_ACTION" "$3" "$4" "$5" "$6" "$7"
 ;;
 
 custom)
@@ -318,10 +375,9 @@ Usage:
 
 EOT
 # Sound error
+$SOUNDS_TOOL alert command_not_recognized_try_again
 touch $TTS_OUTPUT_FILE
-$(basename $0) $TTS_API custom "I do not recognize that command.  Please try again"
-touch $TTS_OUTPUT_FILE
-exit 1
+exit 0
 ;;
 
 esac
@@ -332,14 +388,16 @@ esac
 # Begin announcement
 if [[ -e $TTS_OUTPUT_FILE ]];
 then
-# Mute speaker volume
-$SPEAKER_VOLUME_TOOL all localhost mute
 #
-# Play saved TTS audio
-$TTS_PLAY_CMD $TTS_PLAY_CMD_OPTS $TTS_OUTPUT_FILE
+# Copy saved TTS audio file (without extension) to temp dir i.e. /tmp so it can be accessed by sounds tool
+cp -f $TTS_OUTPUT_FILE $TMPDIR/
 #
-# Unmute speaker volume
-$SPEAKER_VOLUME_TOOL all localhost unmute
+# Play saved TTS audio if concatenate=yes is not specified at CLI
+if [[ "$TTS_CONCATENATE_AUDIO" != "yes" ]];
+then
+ALERT_SOUND_FILE=$(echo ${TTS_OUTPUT_FILE##*/} | sed 's:.mp3::')
+$SOUNDS_TOOL alert $ALERT_SOUND_FILE gain=$SOUNDS_VOLUME_LEVEL
+fi
 
 else
 # Add bogus sound effects file to stop beep if no TTS audio file found
