JambulaTV: Added Internet connectivity check in jambulatv-email tool
*  Prevents unnecessary creation of mail spool files

diff --git a/bin/jambulatv-email b/bin/jambulatv-email
--- a/bin/jambulatv-email
+++ b/bin/jambulatv-email
@@ -12,10 +12,34 @@ EMAIL_GMAIL_CONFIG=/etc/JambulaTV/email-gmail.cfg
 EMAIL_SMTP_AUTH_USERNAME=$EMAIL_SMTP_AUTH_USERNAME
 EMAIL_SMTP_AUTH_PASSWORD=$(echo $EMAIL_SMTP_AUTH_ENCRYPT | base64 -d)
 
+PING_COUNT=1 #9
+PING_IP_ADDRESS=8.8.8.8
+
+
+
+###############
+#  FUNCTIONS  #
+###############
+check_internet_access () {
+# Check for internet connectivity - IMPORTANT: Don't use DNS to ping use actual IP address
+ping -c $PING_COUNT $PING_IP_ADDRESS > /dev/null 2>&1
+EXITVAL=$?
+if [ "$EXITVAL" != "0" ];
+then
+# Quit script, since there's no internet.  Leave exit status at 0 so systemd service works
+echo "JambulaTV Error: There's no Internet.  Please connect first!"
+exit 0
+fi
+}
+
+
 
 #################
 #  MAIN SCRIPT  #
 #################
+# Check for internet firsy
+check_internet_access
+
 # Email Address
 if [ "x$EMAIL_TO_ADDRESS_REMOTE" = "x" ];
 then
