JambulaTV: Add enhancements to jambulatv-whatsapp tool to make it easier to            troubleshoot when messages or images are not sent
* Add logging capabilities to tool including debug (-L) option to yowsup-cli

* Add waiting period, in cases where another instance of this tool is running

* Force users to always run this tool as root i.e. sudo

* Add extra login /L into WhatsApp servers when sending images

diff --git a/bin/jambulatv-whatsapp b/bin/jambulatv-whatsapp
--- a/bin/jambulatv-whatsapp
+++ b/bin/jambulatv-whatsapp
@@ -8,6 +8,8 @@ COUNTRY_MCC_MNC_RAW_FILE=/tmp/mcc_mnc_raw.csv
 
 WHATSAPP_SCRIPT=/usr/bin/jambulatv-whatsapp
 WHATSAPP_CREDENTIALS_CONFIG=/etc/JambulaTV/messaging-whatsapp.cfg
+WHATSAPP_CMD=$(which yowsup-cli)
+WHATSAPP_LOG_FILE=/var/log/JambulaTV/whatsapp.log
 WHATSAPP_METHOD_NAME=$1
 WHATSAPP_TEXT_MESSAGE="$2"
 WHATSAPP_IMAGE_PATH="$2"
@@ -17,12 +19,42 @@ WHATSAPP_REGISTRATION_METHOD=sms
 PING_TIMEOUT=3 #9
 PING_IP_ADDRESS=8.8.8.8
 
+ANOTHER_INSTANCE_TEMP_FILE=/tmp/whatapp_processes_running
+
 
 
 ###############
 #  FUNCTIONS  #
 ###############
+
+start_logging () {
+# Make log file writeable by all
+sudo chmod a+w $WHATSAPP_LOG_FILE
+# Start logging
+cat >> $WHATSAPP_LOG_FILE <<EOF
+
+------------------------------------
+Date:  $(date)
+------------------------------------
+EOF
+exec 2>> $WHATSAPP_LOG_FILE
+}
+
+check_if_root () {
+if [ "`whoami`" != "root" ];
+then
+clear
+logger -s -t $(basename $0) "Incorrect user! You need to run this tool as root. Try again using sudo" 
+tail -1 $WHATSAPP_LOG_FILE
+exit 1
+fi
+}
+
 usage () {
+# Check who is running this tool
+check_if_root
+
+# CLI arguments
 clear
 if [ "x$WHATSAPP_METHOD_NAME" = "x" ];
 then
@@ -71,6 +103,27 @@ ERROR ($(basename $basename $0)): Unable to connect to WhatsApp. Check your Inte
 EOF
 exit 0
 fi
+}
+
+pre_start_tasks () {
+usage
+#
+check_internet_access
+#
+# Wait if another instance of me is running
+while [ -e "$ANOTHER_INSTANCE_TEMP_FILE" ];
+do
+logger -s -t $(basename $0) "Another WhatsApp instance is running, waiting a bit"
+sleep 10
+done
+#
+# Create temp file to prevent other WhatsApp instances from neing started while
+# this one is in progress
+[ -e "$ANOTHER_INSTANCE_TEMP_FILE" ] || touch $ANOTHER_INSTANCE_TEMP_FILE
+}
+
+post_clean_up_tasks () {
+[ -e "$ANOTHER_INSTANCE_TEMP_FILE" ] && rm -f $ANOTHER_INSTANCE_TEMP_FILE
 }
 
 registration_status () {
@@ -215,14 +268,13 @@ MOBILE_NETWORK_CODE=$MOBILE_NETWORK_CODE
 EOF
 
 # Request for PIN code using SMS
-yowsup-cli registration -d -E android -m $MOBILE_COUNTRY_CODE -n $MOBILE_NETWORK_CODE -p $WHATSAPP_PHONE_NUMBER_SENDER -C $TELEPHONE_COUNTRY_CODE -r $WHATSAPP_REGISTRATION_METHOD 2>&1 | grep -i "status: fail" 
+$WHATSAPP_CMD registration -d -L $WHATSAPP_LOG_FILE -E android -m $MOBILE_COUNTRY_CODE -n $MOBILE_NETWORK_CODE -p $WHATSAPP_PHONE_NUMBER_SENDER -C $TELEPHONE_COUNTRY_CODE -r $WHATSAPP_REGISTRATION_METHOD 2>&1 | grep -i "status: fail" 
 REQUEST_CODE_STATUS=$?
 if [[ "$REQUEST_CODE_STATUS" = "0" ]];
 then
 # Notify of failure and quit
 cat <<EOF
-echo "$(basename $0): Failed to get registration code.  Please check for actual Yowsup error message"
-logger "$(basename $0): Failed to get registration code.  Please check for actual Yowsup error message"
+logger -s -t $(basename $0) "Failed to get registration code.  Please check for actual Yowsup error message"
 EOF
 exit 1
 fi
@@ -240,7 +292,7 @@ echo "Error:  Please register this device for whatsapp first before you can conf
 exit 1
 fi
 # Confirm using sent PIN code
-yowsup-cli registration -d -E android -p $WHATSAPP_PHONE_NUMBER_SENDER -C $TELEPHONE_COUNTRY_CODE -R $WHATSAPP_REGISTRATION_CODE
+$WHATSAPP_CMD registration -d -L $WHATSAPP_LOG_FILE -E android -p $WHATSAPP_PHONE_NUMBER_SENDER -C $TELEPHONE_COUNTRY_CODE -R $WHATSAPP_REGISTRATION_CODE
 }
 
 send_pre_check () {
@@ -263,7 +315,7 @@ send_message () {
 # Pre-checks before sending
 send_pre_check
 # Send message to Whatsapp recipient
-yowsup-cli demos -d -l "$WHATSAPP_PHONE_NUMBER_SENDER:$WHATSAPP_ENCRYPTED_PASSWORD" -s $WHATSAPP_PHONE_NUMBER_RECIPIENT "$WHATSAPP_TEXT_MESSAGE"
+$WHATSAPP_CMD demos -d -L $WHATSAPP_LOG_FILE -l "$WHATSAPP_PHONE_NUMBER_SENDER:$WHATSAPP_ENCRYPTED_PASSWORD" -s $WHATSAPP_PHONE_NUMBER_RECIPIENT "$WHATSAPP_TEXT_MESSAGE"
 }
 
 send_image () {
@@ -271,10 +323,12 @@ send_image () {
 send_pre_check
 # Send image to Whatsapp recipient
 /usr/bin/expect -c "
-spawn yowsup-cli demos -y -d -l \"$WHATSAPP_PHONE_NUMBER_SENDER:$WHATSAPP_ENCRYPTED_PASSWORD\"; 
+spawn $WHATSAPP_CMD demos -y -d -L $WHATSAPP_LOG_FILE -l \"$WHATSAPP_PHONE_NUMBER_SENDER:$WHATSAPP_ENCRYPTED_PASSWORD\"; 
 expect \[offline\];
 
 # Connect/ Quick login
+send /L\n;
+send /L\n;
 send /L\n;
 expect eof;
 #
@@ -324,9 +378,10 @@ EOF
 #################
 #  MAIN SCRIPT  #
 #################
-usage
 
-check_internet_access
+start_logging
+
+pre_start_tasks
 
 case $WHATSAPP_METHOD_NAME in
 [Rr][Ee][Gg][Ii][Ss][Tt][Ee][Rr])
@@ -347,3 +402,5 @@ echo "Usage:  ./`basename $0` [register]|[sendmessage]|[sendimage]
 exit 1
 ;;
 esac
+
+post_clean_up_tasks
